version: "3.8"

services:
  dejavu:
    build: .
    restart: always

  nginx_proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/etc/static
    ports:
      - 8080:80
    depends_on:
      - dejavu
