name: "build"

on: ["push", "pull_request"]

jobs:
  build-docker:
    runs-on: "ubuntu-latest"

    steps:
    - uses: "actions/checkout@v2"

    - name: "build"
      run: "docker build -t dejavu ."

    - name: "export"
      run: "docker save dejavu > dejavu.tar"

    - uses: "actions/upload-artifact@v2"
      with:
        name: "docker image"
        path: "dejavu.tar"
